---
layout: page
title: "제8회 지방선거 2022년"
subtitle: "경기도 초등학교"
author:
- name: "이광춘"
  affiliation: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
date: "`r Sys.Date()`"
tags: ["지방선거", "지선"]
output:
  html_document: 
    include:
      after_body: footer.html
      before_body: header.html
      in_header: google_analytics.html
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: hide
    number_section: true
    self_contained: true
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')
library(tidyverse)
library(rvest)
library(lubridate)
library(ggrepel)
library(sf)
library(geogrid)
library(tilemaps)
library(httr)
library(rvest)
```

# .초등학교 위치 {#local-gg-school}

## .경기도 공공데이터 {#local-gg-school-public}

```{r gg-school-public}

gg_url <- glue::glue("https://openapi.gg.go.kr/ElmschlM",
                     "?KEY={Sys.getenv('DATA_GG_APIKEY')}",
                     "&Type=json",
                     "&pIndex=1",
                     "&pSize=1000",
                     "&SIGUN_NM={URLencode('가평군')}",
                     "&SIGUN_CD=41820")

gg_school_list <- GET(gg_url) %>% 
  content(as="text") %>% 
  jsonlite::fromJSON(.)

gg_school_raw <- gg_school_list %>% 
  pluck("ElmschlM") %>% 
  pluck("row") %>% 
  .[[2]] %>% 
  as_tibble()

gg_school_raw

```


## .변수명 {#local-gg-school-public-varname}

```{r gg-school-public-varname}

gg_school_varname <- readxl::read_excel("data/공공데이터/경기도/초등학교 현황_오픈API명세서.xls.xlsx", skip = 24) %>% 
  janitor::clean_names(ascii = FALSE) %>% 
  slice(1:12)

gg_school_varname

gg_school_tbl <- gg_school_raw %>% 
  set_names(gg_school_varname$출력_설명) %>% 
  janitor::clean_names(ascii = FALSE) %>% 
  mutate(across(wgs84위도:wgs84경도, parse_number))

gg_school_tbl

```


# .지도 {#map-school}

##. 면적지도 {#map-school-gapyung}

amd_cd == 시군코드 (5자리)


```{r gapyung-map}

precinct_raw <- st_read("data/tilemap/HangJeongDong_ver20220309.geojson")

gapyung_sf <- precinct_raw %>% 
  filter(ELEC_GU == "가평군") %>% 
  mutate(시군코드 = str_sub(adm_cd2, 1, 5))

gapyung_sf %>% 
  ggplot() +
    geom_sf()
```


##. 학교위치-매핑 {#map-school-gapyung-mapping}


```{r gapyung-map-data}

gapyung_data_sf <- gapyung_sf %>% 
  group_by(시군코드, sidonm, sggnm) %>% 
  summarise(geometry = sf::st_union(geometry)) %>% 
  ungroup() %>% 
  left_join(gg_school_tbl, by = c("시군코드"))
  

gapyung_data_sf %>% 
  ggplot() +
    geom_sf() +
    geom_point(aes(x = wgs84위도, y = wgs84경도)) +
    geom_text(aes(x = wgs84위도, y = wgs84경도, label = 시설명), vjust = -1.5, size = 3)  +
    theme(
        text = element_text(family = "NanumGothic"),
        plot.tag.position = c(0.85, .97),
        legend.position = "top",
        legend.title=element_text(size=15), 
        legend.text=element_text(size=13),
        strip.text.x = element_text(size = rel(1.3), colour = "black", family = "NanumBarunpen", face="bold"),
        axis.text.y = element_text(size = rel(1.5), colour = "gray35", family = "NanumBarunpen", face="bold"),
        axis.text.x = element_text(size = rel(1.3), colour = "black", family = "NanumBarunpen", face="bold"),
        strip.background=element_rect(fill="gray95"),
        plot.title=element_text(size=25, face="bold", family = "NanumBarunpen"),
        plot.subtitle=element_text(face="bold", size=17, colour="grey10", family = "NanumBarunpen"))   +
      theme_void() +
    labs(title = "경기도 가평군 초등학교")


```

